# changing from ctrl-b to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

 # 0 is too far from ` ;)
set -g base-index 1
set -g pane-base-index 1

set -g status-left-length 30 # big names were trunced
set -g renumber-windows on # renumber windows sequentially after closing any of them
set -g default-terminal "screen-256color" # colors on tmux
set -s escape-time 0 # escape zero timeout
set -g history-limit 100000 # increase scrollback lines
set -g display-panes-time 300000 # display-panes showtime is too short

setw -g mode-keys vi # act like vim
setw -g monitor-activity on # notifications

# disable autorename of windows
set-window-option -g automatic-rename off
set-option -g allow-rename off

bind r source-file ~/.tmux.conf # Reload tmux config

