# fix tmux pbcopy problem
set-option -g default-command "D > /dev/null 2>&1; reattach-to-user-namespace -l bash"

# changing from ctrl-b to ctrl-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# 0 is too far from ` ;)
set -g base-index 1
set -g pane-base-index 1

set -g status-left-length 30 # big names were trunced
set -g renumber-windows on # renumber windows sequentially after closing any of them
set -g default-terminal "screen-256color" # colors on tmux
set -g history-limit 100000 # increase scrollback lines
set -g display-panes-time 300000 # display-panes showtime is too short
setw -g mode-keys vi # act like vim
setw -g monitor-activity on # notifications

# disable autorename of windows
set-window-option -g automatic-rename off
set-option -g allow-rename off

# some vim keybinginds
bind-key k select-pane -U
bind-key j select-pane -D
bind-key h select-pane -L
bind-key l select-pane -R

bind-key p paste-buffer
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi V send-keys -X start-of-line\; send -X begin-selection\; send-keys -X end-of-line

bind-key C-K resize-pane -U
bind-key C-J resize-pane -D
bind-key C-H resize-pane -L
bind-key C-L resize-pane -R

bind-key K resize-pane -U 5
bind-key J resize-pane -D 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\ select-pane -l
