#!/usr/bin/env bash
asdf_current() {
    lang=$1
    current=$(pwd)
    root=$(dirname $HOME)

    while test "$current" != "$root"; do
        if test -e $current/.tool-versions; then
            file=$current/.tool-versions
            break
        fi
        current=$(builtin cd $current/..; pwd)
    done

    while IFS= read -r ver; do
        if [[ "$ver" =~ "$lang" ]] ; then
            echo $ver | cut -d " " -f 2
            return 0
        fi
    done < "$file"
}

asdf_current "$@"
