format = """\
$directory\
([>](fg-neon-black)\
$git_status\
)\
[>](fg-neon-black)\
$character\
$line_break\
[> ](fg-neon-black)"""

add_newline = false
command_timeout = 3000

palette = 'tokyo-night-moon'

[palettes.tokyo-night-moon]
bg-border = '#3b4261'
bg-middle = '#2f334d'
bg-inactive = '0'
fg-black = '0'
fg-red = '1'
fg-green = '2'
fg-yellow = '3'
fg-blue = '4'
fg-purple = '5'
fg-cyan = '6'
fg-white = '7'
fg-neon-black = '240'
fg-neon-red = '196'
fg-neon-green = '46'
fg-neon-yellow = '226'
fg-neon-blue = '39'
fg-neon-purple = '201'
fg-neon-cyan = '49'
fg-neon-white = '231'
fg-orange = '208'
fg-vermilion = '202'
fg-lime = '149'
fg-lavender = '147'
fg-periwinkle = '105'

[character]
disabled = false
format = '$symbol'
success_symbol = '[I](bold green)'
error_symbol = '[I](bold green)'
vimcmd_symbol = '[N](bold blue)'
vimcmd_replace_one_symbol = '[R](bold red)'
vimcmd_replace_symbol = '[R](bold red)'
vimcmd_visual_symbol = '[V](bold purple)'

[directory]
disabled = false
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)"""
before_repo_root_style = 'white'
repo_root_style = 'bold cyan'
format = '[$path]($style)'
style = 'bold dimmed cyan'
read_only = ' ro'
truncate_to_repo = true
truncation_symbol = ''

[git_status]
disabled = false
format = '([$all_status$ahead_behind]($style))'
style = 'bold'
conflicted = '[!=${count}](bold fg-neon-purple)'
ahead = '[>${count}](bold fg-green)'
behind = '[<${count}](bold fg-red)'
diverged = '[>${ahead_count}](bold fg-green)[<${behind_count}](bold fg-red)'
up_to_date = '[=](bold fg-green)'
untracked = '[?${count}](bold fg-blue)'
stashed = '[\$${count}](bold fg-purple)'
modified = '[!${count}](bold fg-yellow)'
staged = '[+${count}](bold fg-neon-green)'
renamed = '[r${count}](bold fg-cyan)'
deleted = '[x${count}](bold fg-neon-red)'
typechanged = '[t${count}](bold fg-neon-blue)'

[status]
disabled = false
format = '[$symbol$status]($style)'
symbol = 'err '
failure_style = 'bold red'
success_style = 'bold green'
success_symbol = 'ok '
not_executable_symbol = 'noexe '
not_found_symbol = 'notfound '
signal_symbol = 'sig '

[line_break]
disabled = false
