format = """\
$character\
[ \
$directory\
$fill\
](bg:bg-middle)\
([ \
$status\
](black bg:green))\
$line_break"""

add_newline = false
command_timeout = 3000

palette = 'tokyo-night-moon'

[palettes.tokyo-night-moon]
bg-border = '#3b4261'
bg-middle = '#2f334d'
bg-inactive = '0'

[character]
disabled = false
format = '$symbol'
success_symbol = '[ I ](bold black bg:green)'
error_symbol = '[ I ](bold black bg:green)'
vimcmd_symbol = '[ N ](bold black bg:blue)'
vimcmd_replace_one_symbol = '[ R ](bold black bg:red)'
vimcmd_replace_symbol = '[ R ](bold black bg:red)'
vimcmd_visual_symbol = '[ V ](bold black bg:purple)'

[fill]
disabled = false
style = 'bg:bg-middle'
symbol = ' '

[directory]
disabled = false
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)"""
before_repo_root_style = 'white bg:bg-middle'
repo_root_style = 'bold cyan bg:bg-middle'
format = '[$path]($style)'
style = 'bold dimmed cyan bg:bg-middle'
read_only = '🔒'
truncate_to_repo = true
truncation_symbol = ''

[status]
disabled = false
format = '[$symbol$status ]($style)'
symbol = '❗'
failure_style = 'bold black bg:green'
success_style = 'bold black bg:green'
success_symbol = '✅'
not_executable_symbol = '🚫'
not_found_symbol = '❓'
signal_symbol = '💥'

[line_break]
disabled = false
